version: '3'
services:
  app:
    container_name: 352test
    restart: always
    build: .
    ports:
      - "8080:9876"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
