version: "3"
services:
  product-service:
    container_name: product-service
    build: ./product_service
    ports:
      - "8080:9876"
    links:
      - mongo

  db-service:
    container_name: db-service
    build: ./db_service
    ports:
      - "8081:9876"
    links:
      - mongo

  account-service:
    container_name: account-service
    build: ./account_service
    ports:
      - "8082:9876"
    links:
      - mongo

  interaction-service:
    container_name: interaction-service
    build: ./interaction_service
    ports:
      - "8083:9876"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
