version: "3"
services:
  app:
    container_name: buyo-backend
    build: .
    ports:
      - "8080:9876"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
